### ISSUE TITLE
Built-in resources

### ISSUE THREAD

**Issue by turbocat2001** [rgimad/gravity_defied_cpp#15]
Hi @AntonEvmenenko! @rgimad  and I had an idea to make the binary more autonomous, that is, to include resources in it.  Of course, the best option would be to use Windows Resources, but there is nothing similar for Linux.  Therefore, my idea is to compile resources into a binary.  There are two ways:
 1. Use GNU-asm (I already tried this idea, but it looks a bit ugly). 
 2. Add a CMake target that will convert resources to C arrays.

**Comment by AntonEvmenenko** [comment]
Well, I don't know anything about this topic, so please feel free to choose any suitable way to implement it :)

**Comment by AntonEvmenenko** [comment]
Can we close this issue? It seems like it was resolved in #18
